<?php

namespace AppBundle\Repository;

/**
 * BreadCrumpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreadCrumpsRepository extends \Doctrine\ORM\EntityRepository
{
}
