<?php

namespace AppBundle\Repository;

/**
 * EmployesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployesRepository extends \Doctrine\ORM\EntityRepository
{
}
