<?php

namespace AppBundle\Repository;

/**
 * FeaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturesRepository extends \Doctrine\ORM\EntityRepository
{
}
