<?php

namespace AppBundle\Repository;

/**
 * GalerryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerryRepository extends \Doctrine\ORM\EntityRepository
{
}
