<?php

namespace AppBundle\Repository;

/**
 * GalleryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
