<?php

namespace AppBundle\Repository;

/**
 * LeagueGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends \Doctrine\ORM\EntityRepository
{
    public function createLeagueGrouppQueryBuilder()
    {
        return $this->createQueryBuilder('league')
            ->andWhere('groupp = groupp.id')
            ->setParameter('groupp.id', true);
    }
    
}
