<?php

namespace AppBundle\Repository;

/**
 * LeagueGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
