<?php

namespace AppBundle\Repository;

/**
 * MemberGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
