<?php

namespace AppBundle\Repository;

/**
 * OurServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
