<?php

namespace AppBundle\Repository;

/**
 * placeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class placeRepository extends \Doctrine\ORM\EntityRepository
{
}
