<?php

namespace AppBundle\Repository;

/**
 * teamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
