<?php

namespace AppBundle\Repository;

/**
 * WhyUsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhyUsRepository extends \Doctrine\ORM\EntityRepository
{   
}
