imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: sr

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
#        - bootstrap_3_layout.html.twig
        - bootstrap_3_horizontal_layout.html.twig
#        - form_div_layout.html.twig
#        - form_table_layout.html.twig
#        - foundation_5_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
    
vich_uploader:
    db_driver: orm  
    
    mappings:
        user_upload:
            uri_prefix:         /web/upload/images
            upload_destination: '%kernel.root_dir%/../web/upload/images'
            namer:              vich_uploader.namer_origname
            
        admin_upload:
            uri_prefix:         /web/public/Front/images
            upload_destination: '%kernel.root_dir%/../web/public/Front/images'
            namer:              vich_uploader.namer_origname     
            
assetic:
  
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
   
    filters:
        cssrewrite: ~
        uglifyjs:
            bin:  %kernel.root_dir%\Resources\node_modules\uglify-js\bin\uglifyjs
        uglifycss:
            bin: %kernel.root_dir%\Resources\node_modules\uglifycss\uglifycss
            
    assets:
        jq_front:
            inputs:
                - '@AppBundle/Resources/skin/front/js/jquery.min.js' 
#                - '@AppBundle/Resources/skin/front/js/jquery-migrate-3.0.0.min.js'  
                - '@AppBundle/Resources/skin/front/js/app.js'
                - '@AppBundle/Resources/skin/front/js/bootstrap.min.js'
                - '@AppBundle/Resources/skin/front/js/bootstrap-slider.js'  
                - '@AppBundle/Resources/skin/front/js/components.js'
                - '@AppBundle/Resources/skin/front/js/components-shop.js'              
                - '@AppBundle/Resources/skin/front/js/isotope.pkgd.min.js'
                - '@AppBundle/Resources/skin/front/js/imagesloaded.pkgd.min.js'
                - '@AppBundle/Resources/skin/front/js/isotope-grid.js'                              
                - '@AppBundle/Resources/skin/front/js/jquery-migrate.min.js'                
                - '@AppBundle/Resources/skin/front/js/jquery.easing.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.cubeportfolio.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.counterup.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.waypoints.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.fancybox.pack.js'
                - '@AppBundle/Resources/skin/front/js/jquery.smooth-scroll.js'
                - '@AppBundle/Resources/skin/front/js/jquery.themepunch.revolution.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.themepunch.tools.min.js'
                - '@AppBundle/Resources/skin/admin/jss/js.cookie.min.js'                
                - '@AppBundle/Resources/skin/front/js/owl.carousel.min.js'
                - '@AppBundle/Resources/skin/front/js/packery-mode.pkgd.min.js'               
                - '@AppBundle/Resources/skin/front/js/revolution.extension.slideanims.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.layeranimation.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.navigation.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.parallax.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.video.min.js'
                - '@AppBundle/Resources/skin/front/js/reveal-animate.js'               
                - '@AppBundle/Resources/skin/front/js/slider-8.js'
                - '@AppBundle/Resources/skin/front/js/typed.min.js'              
                - '@AppBundle/Resources/skin/front/js/wow.min.js'
                
        jq_front_home:
            inputs:   
#                 <!-- BEGIN: CORE PLUGINS -->
                - '@AppBundle/Resources/skin/front/js/jquery.min.js' 
                - '@AppBundle/Resources/skin/front/js/jquery-migrate.min.js' 
                - '@AppBundle/Resources/skin/front/js/bootstrap.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.easing.min.js'
                - '@AppBundle/Resources/skin/front/js/wow.min.js'
                - '@AppBundle/Resources/skin/front/js/reveal-animate.js' 
#                <!-- END: CORE PLUGINS -->
#                <!-- BEGIN: LAYOUT PLUGINS -->
                - '@AppBundle/Resources/skin/front/js/jquery.themepunch.revolution.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.themepunch.tools.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.slideanims.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.layeranimation.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.navigation.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.parallax.min.js'
                - '@AppBundle/Resources/skin/front/js/revolution.extension.video.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.cubeportfolio.min.js'
                - '@AppBundle/Resources/skin/front/js/owl.carousel.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.waypoints.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.counterup.min.js'
                - '@AppBundle/Resources/skin/front/js/jquery.fancybox.pack.js'
                - '@AppBundle/Resources/skin/front/js/jquery.smooth-scroll.js'
                - '@AppBundle/Resources/skin/front/js/typed.min.js' 
                - '@AppBundle/Resources/skin/front/js/bootstrap-slider.js' 
                - '@AppBundle/Resources/skin/admin/jss/js.cookie.min.js'   
#                <!-- END: LAYOUT PLUGINS -->
#                <!-- BEGIN: THEME SCRIPTS -->
                - '@AppBundle/Resources/skin/front/js/components.js'
                - '@AppBundle/Resources/skin/front/js/components-shop.js' 
                - '@AppBundle/Resources/skin/front/js/app.js'
#                <!-- END: THEME SCRIPTS -->
#               <!-- BEGIN: PAGE SCRIPTS -->
                - '@AppBundle/Resources/skin/front/js/slider-8.js'
                - '@AppBundle/Resources/skin/front/js/isotope.pkgd.min.js'
                - '@AppBundle/Resources/skin/front/js/imagesloaded.pkgd.min.js'
                - '@AppBundle/Resources/skin/front/js/packery-mode.pkgd.min.js'
                - '@AppBundle/Resources/skin/front/js/isotope-grid.js'    
#               <!-- END: PAGE SCRIPTS -->
                      
        jq_admin:
            inputs:  
                -  '@AppBundle/Resources/skin/admin/jss/jquery-3.2.1.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery-migrate-3.0.0.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/js.cookie.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.blockui.min.js'            
                -  '@AppBundle/Resources/skin/admin/jss/bootstrap.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.slimscroll.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/bootstrap-switch.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/moment.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/daterangepicker.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/morris.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/raphael-min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.waypoints.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.counterup.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/amcharts.js'
                -  '@AppBundle/Resources/skin/admin/jss/serial.js'
                -  '@AppBundle/Resources/skin/admin/jss/pie.js'
                -  '@AppBundle/Resources/skin/admin/jss/radar.js'
                -  '@AppBundle/Resources/skin/admin/jss/light.js'
                -  '@AppBundle/Resources/skin/admin/jss/patterns.js'
                -  '@AppBundle/Resources/skin/admin/jss/chalk.js'
                -  '@AppBundle/Resources/skin/admin/jss/ammap.js'
                -  '@AppBundle/Resources/skin/admin/jss/worldLow.js'
                -  '@AppBundle/Resources/skin/admin/jss/amstock.js'
                -  '@AppBundle/Resources/skin/admin/jss/fullcalendar.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/horizontal-timeline.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.flot.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.flot.resize.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.flot.categories.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.easypiechart.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.sparkline.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.vmap.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.vmap.sampledata.js'
                -  '@AppBundle/Resources/skin/admin/jss/app.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/dashboard.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/layout.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/demo.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/quick-sidebar.js'
                -  '@AppBundle/Resources/skin/admin/jss/quick-nav.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/datatable.js'
                -  '@AppBundle/Resources/skin/admin/jss/datatables.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/datatables.bootstrap.js'
                -  '@AppBundle/Resources/skin/admin/jss/table-datatables-scroller.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/table-datatables-responsive.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.repeater.min.js'               
                -  '@AppBundle/Resources/skin/admin/jss/bootstrap-datepicker.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/form-repeater.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/components-date-time-pickers.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/components-select2.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/select2.full.min.js'   
                -  '@AppBundle/Resources/skin/admin/jss/jquery.validate.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/additional-methods.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/jquery.backstretch.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/login-5.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/respond.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/excanvas.min.js'
                -  '@AppBundle/Resources/skin/admin/jss/ie8.fix.min.js'
                
                
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "sasam09@gmail.com"
        sender_name: "JOBlider"   
    registration:
        confirmation:
            from_email:
                address: "sasam09@gmail.com"
                sender_name: "JOB lider"    
                
