admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:  admin

front:
    resource: "@AppBundle/Resources/config/routing/front.yml"
    prefix:  
        
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 
    prefix:     
        
   
