home:
    path:     /
    defaults: { _controller: "AppBundle:Front/Home:index" }
    methods:  GET

trener_detail:
    path:     /trener/{slug}/
    defaults: { _controller: "AppBundle:Front/teamMember:detail" }
    methods:  GET
    
team:
    path:     /tim-trenera/
    defaults: { _controller: "AppBundle:Front/teamMember:index" }
    methods:  GET   
    
place:
    path:     /raspored-treninga/
    defaults: { _controller: "AppBundle:Front/place:index" }
    methods:  GET  
    
place_detail:
    path:     /lokacija/{slug}/
    defaults: { _controller: "AppBundle:Front/place:detail" }
    methods:  GET    
    
pricing:
    path:     /cenovnik/
    defaults: { _controller: "AppBundle:Front/Pricing:index" }
    methods:  GET     
    
league:
    path:     /takmicenja/
    defaults: { _controller: "AppBundle:Front/League:index" }
    methods:  GET  
    
league_detail:
    path:     /takmicenja/{slug}/
    defaults: { _controller: "AppBundle:Front/League:detail" }
    methods:  GET     
    
game_detail:
    path:     /takmicenja/{id}/{name}/utakmice/
    defaults: { _controller: "AppBundle:Front/Game:detail" }
    methods:  GET  
    
about:
    path:     /o-nama/
    defaults: { _controller: "AppBundle:Front/Company:index" }
    methods:  GET
    
contact:
    path:     /kontakt/
    defaults: { _controller: "AppBundle:Front/Contact:index" }
    methods:  GET    
    
galerys:
    path:     /galerije/
    defaults: { _controller: "AppBundle:Front/MainGallery:index" }
    methods:  GET   
    
allblog:
    path:     /vesti/
    defaults: { _controller: "AppBundle:Front/Blog:index" }
    methods:  GET  
    
blog:
    path:     /vesti/{id}/{name}/
    defaults: { _controller: "AppBundle:Front/Blog:detail" }
    methods:  GET        
    
    
 
        
  
    